export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const CHECK_TOKEN_REQUEST = "CHECK_TOKEN_REQUEST";
export const CHECK_TOKEN_SUCCESS = "CHECK_TOKEN_SUCCESS";
export const CHECK_TOKEN_FAILURE = "CHECK_TOKEN_FAILURE";

export const SAVE_USERNAME_REQUEST = "SAVE_USERNAME_REQUEST";
export const SAVE_USERNAME_SUCCESS = "SAVE_USERNAME_SUCCESS";
export const SAVE_USERNAME_FAILURE = "SAVE_USERNAME_FAILURE";

export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const GET_DASHBOARD_REQUEST = "GET_DASHBOARD_REQUEST";
export const GET_DASHBOARD_SUCCESS = "GET_DASHBOARD_SUCCESS";
export const GET_DASHBOARD_FAILURE = "GET_DASHBOARD_FAILURE";

export const POLL_DATA_REQUEST = "POLL_DATA_REQUEST";
export const POLL_DATA_SUCCESS = "POLL_DATA_SUCCESS";
export const POLL_DATA_FAILURE = "POLL_DATA_FAILURE";

export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const NEW_POST = "NEW_POST";
export const NEW_COMMENTS = "NEW_COMMENTS";
export const NEW_CHARTS_DATA = "NEW_CHARTS_DATA";

export const UPDATE_POST = "UPDATE_POST";
export const UPDATE_COMMENTS = "UPDATE_COMMENTS";
export const UPDATE_CHARTS = "UPDATE_CHARTS";
